# Verwenden Sie das offizielle MySQL-Image als Basis
FROM mysql:latest

# Setzen Sie Umweltvariablen für die MySQL-Konfiguration
ENV MYSQL_ROOT_PASSWORD admin123
ENV MYSQL_DATABASE MLdeploy
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD admin
