name: Deploy FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy Repository to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "."
        target: "/home/masterries/github/MedicalMLDeploy"
    - name: Restart FastAPI App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/masterries/github/MedicalMLDeploy/backend
          # Stellen Sie sicher, dass Sie hier die richtigen Befehle zum Starten Ihrer Anwendung verwenden
          # uvicorn backendapi:app --reload

